spring.application.name=caris-sso

# ===============================
# =  MYBATIS
# ===============================
#mybatis.mapper-locations=classpath*:/mappers/*/*Mapper.xml
#mybatis.config-location=classpath:mybatis-config.xml
mybatis.config-location=mybatis-config.xml
mybatis.properties.development.url=jdbc:postgresql://10.0.0.127:5436/caris-sso
mybatis.properties.development.username=postgres
mybatis.properties.development.password=postgres
mybatis.properties.development.driver=org.postgresql.Driver

# ===============================
# =  USER SYNC
# ===============================
user.sync.secret=${USER_SYNC_SECRET:h2CKQI82HIWgPmspm8nAFY9a}